// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using carCenter.models.dbcontext;

namespace carCenter.Migrations
{
    [DbContext(typeof(CarCenterDbContext))]
    partial class CarCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("carCenter.models.clientes.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Celular")
                        .HasColumnType("Varchar (20)")
                        .HasColumnName("celular");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("Direccion")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .HasColumnType("Varchar (20)")
                        .HasColumnName("documento");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("segundo_nombre");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("Varchar (255)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
